### PR TITLE
Kkobel work

### PR DESCRIPTION
**Pull request by KKobel**
A big update, sorry.
I will make the subsequent changes smaller.

### CODE REVIEW

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — APPROVED** [review]
These look ok.   I home I'm doing this right.

**Review by bbarnt — CHANGES_REQUESTED** [review]
Please fill in header comments for GetVariableValue().

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — COMMENTED** [review]
Why leave the "OLD" definition of StatusLed() in an ifdef?  Won't version control keep the old code?

**Review by bbarnt — COMMENTED** [review]
Do we really need to add dead code?  (line 808)?

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — COMMENTED** [review]
How about added a comment/header to each function to describe the difference, or use a better descriptive name than "2"?

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — CHANGES_REQUESTED** [review]
Why clutter up the code with dead comments?  (i.e get rid of all the //#define lines)

**Review by bbarnt — COMMENTED** [review]
Why are we added a commented out forward definition?

**Review by bbarnt — COMMENTED** [review]
Why are we added a commented out forward definition?

**Review by bbarnt — APPROVED** [review]
Function description?

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — APPROVED** [review]

**Review by bbarnt — APPROVED** [review]

**Comment by KKobel** [comment]
Another update prior to getting the new colaberators going

**Pull request merged**
